### ISSUE TITLE
BugFix: improve dark mode function

### ISSUE THREAD

**Issue by flxtagi** [smartive-education/app-pizza-hawaii#128]
get rid of two useEffect and make it a bit cleaner

**Comment by flxtagi** [comment]
Warning: viewport meta tags should not be used in _document.js's <Head>. https://nextjs.org/docs/messages/no-document-viewport-meta

**Comment by rudigier** [comment]
Great input. Thank you!

**Comment by rudigier** [comment]
Should be done with #114
